apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb  #TO CONNECT TO THE POD through label
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
